"""Regenerate docs/mockup/locales.js from app/locales/*.json (the mockup opens from disk, so it
cannot fetch the catalogs itself), and optionally bundle the mockup into one self-contained HTML
file for sharing.

    python scripts/build_mockup.py            write docs/mockup/locales.js
    python scripts/build_mockup.py --bundle   also write docs/mockup/dist/stableinternet-mockup.html
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MOCKUP = ROOT / "docs" / "mockup"


def locales_js() -> str:
    catalogs = {path.stem: json.loads(path.read_text(encoding="utf-8"))
                for path in sorted((ROOT / "app" / "locales").glob("*.json"))}
    return ("// Generated by scripts/build_mockup.py from app/locales/*.json - do not edit.\n"
            "window.LOCALES = " + json.dumps(catalogs, ensure_ascii=False) + ";\n")


def bundle(html: str, files: dict[str, str]) -> str:
    """Inline the stylesheets and scripts the page references."""
    def css(match: re.Match) -> str:
        return "<style>\n" + files[match.group(1)] + "\n</style>"

    def js(match: re.Match) -> str:
        return "<script>\n" + files[match.group(1)].replace("</script", "<\\/script") + "\n</script>"
    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', css, html)
    return re.sub(r'<script src="([^"]+)"></script>', js, html)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bundle", action="store_true")
    args = ap.parse_args()
    generated = locales_js()
    (MOCKUP / "locales.js").write_text(generated, encoding="utf-8")
    print("wrote docs/mockup/locales.js")
    if args.bundle:
        files = {"../../web/tokens.css": (ROOT / "web" / "tokens.css").read_text(encoding="utf-8"),
                 "mockup.css": (MOCKUP / "mockup.css").read_text(encoding="utf-8"),
                 "locales.js": generated,
                 "mockup.js": (MOCKUP / "mockup.js").read_text(encoding="utf-8")}
        out = MOCKUP / "dist" / "stableinternet-mockup.html"
        out.parent.mkdir(exist_ok=True)
        out.write_text(bundle((MOCKUP / "mockup.html").read_text(encoding="utf-8"), files), encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
