"""Generate the Apple app's String Catalogs from app/locales/*.json (ADR-0010).

app/locales stays the single source of user-facing text (ADR-0006). This script writes:

  apple/Steady/Resources/Localizable.xcstrings    the keys under PREFIXES, every language
  apple/Steady/Resources/InfoPlist.xcstrings      Info.plist texts (INFO_PLIST below), every language
  apple/Config/Generated.xcconfig                 the English Info.plist texts, which Base.xcconfig includes
  apple/SteadyKit/Sources/SteadyKit/Localization/MessageCatalog.swift
                                                  parameter order and format spec per key

Named placeholders become positional "%N$@" in the order they first appear in English, so a
translation may reorder them. Swift formats numbers itself and passes every argument as a string,
except "count" in a plural entry, which is passed as an integer ("%lld") so Apple picks the plural
form with each language's own rules.

    python scripts/locales_to_xcstrings.py          write the files
    python scripts/locales_to_xcstrings.py --check  exit 1 if a generated file is out of date
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALES = ROOT / "app" / "locales"
RESOURCES = ROOT / "apple" / "Steady" / "Resources"
XCCONFIG = ROOT / "apple" / "Config" / "Generated.xcconfig"
SWIFT_CATALOG = ROOT / "apple" / "SteadyKit" / "Sources" / "SteadyKit" / "Localization" / "MessageCatalog.swift"

SOURCE_LANGUAGE = "en"
# Windows-only groups (tweaks, installer, watchdog, failover...) are left out until the Apple app needs them.
PREFIXES = ("app.", "time.", "ui.", "diag.")
# Info.plist key -> catalog key. The key must also be in the Info.plist, so its English text goes
# into Generated.xcconfig; InfoPlist.xcstrings then translates it.
INFO_PLIST = {"CFBundleDisplayName": "app.name",
              "NSLocalNetworkUsageDescription": "ui.permission.local_network"}
PLACEHOLDER = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)(?::([^{}]*))?\}")
PLURAL_COUNT = "count"
# Plural categories Apple uses (CLDR) for integer counts; anything else falls back to "other".
PLURAL_CATEGORIES = {"en": ("one", "other"), "de": ("one", "other"), "es": ("one", "other"),
                     "fr": ("one", "other"), "pt-BR": ("one", "other"),
                     "ja": ("other",), "ko": ("other",), "vi": ("other",), "zh-Hans": ("other",)}
HEADER = "Generated by scripts/locales_to_xcstrings.py from app/locales/*.json - do not edit."


def load_catalogs() -> dict[str, dict]:
    catalogs = {path.stem: json.loads(path.read_text(encoding="utf-8")) for path in sorted(LOCALES.glob("*.json"))}
    if SOURCE_LANGUAGE not in catalogs:
        raise SystemExit(f"missing {SOURCE_LANGUAGE}.json")
    return catalogs


def arguments(english: str | dict) -> list[tuple[str, str | None]]:
    """Parameter names in order of first appearance in English, with the English format spec."""
    seen: dict[str, str | None] = {}
    candidates = [english["other"], *english.values()] if isinstance(english, dict) else [english]
    for text in candidates:
        for name, spec in PLACEHOLDER.findall(text):
            seen.setdefault(name, spec or None)
    return list(seen.items())


def to_format(text: str, positions: dict[str, int], plural: bool) -> str:
    """"{loss:.1f}% of {count}" -> "%1$@%% of %arg" (inside a plural form) or "%1$@%% of %2$@"."""
    out, last = [], 0
    for match in PLACEHOLDER.finditer(text):
        out.append(text[last:match.start()].replace("%", "%%"))
        name = match.group(1)
        if name not in positions:   # not in English: keep it visible rather than drop it
            out.append(match.group(0).replace("%", "%%"))
        elif plural and name == PLURAL_COUNT:
            out.append("%arg")
        else:
            out.append(f"%{positions[name]}$@")
        last = match.end()
    out.append(text[last:].replace("%", "%%"))
    return "".join(out)


def unit(value: str) -> dict:
    return {"stringUnit": {"state": "translated", "value": value}}


def localization(lang: str, value: str | dict, english: str | dict, positions: dict[str, int]) -> dict:
    if not isinstance(english, dict):
        return unit(to_format(value.get("other", "") if isinstance(value, dict) else value, positions, False))
    by_category = value if isinstance(value, dict) else {"other": value}
    variations = {}
    for category in PLURAL_CATEGORIES.get(lang, ("one", "other")):
        text = by_category.get(category, by_category.get("other"))
        if text is not None:
            variations[category] = unit(to_format(text, positions, True))
    return {**unit("%#@count@"),
            "substitutions": {PLURAL_COUNT: {"argNum": positions[PLURAL_COUNT], "formatSpecifier": "lld",
                                             "variations": {"plural": variations}}}}


def localizable(catalogs: dict[str, dict]) -> dict:
    english = catalogs[SOURCE_LANGUAGE]
    strings = {}
    for key in sorted(k for k in english if k.startswith(PREFIXES)):
        positions = {name: i for i, (name, _) in enumerate(arguments(english[key]), 1)}
        if isinstance(english[key], dict) and PLURAL_COUNT not in positions:
            raise SystemExit(f"{key}: plural entry without {{{PLURAL_COUNT}}}")
        strings[key] = {"extractionState": "manual",
                        "localizations": {lang: localization(lang, catalog[key], english[key], positions)
                                          for lang, catalog in catalogs.items() if key in catalog}}
    return {"sourceLanguage": SOURCE_LANGUAGE, "strings": strings, "version": "1.0"}


def info_plist(catalogs: dict[str, dict]) -> dict:
    strings = {}
    for plist_key, key in INFO_PLIST.items():
        texts = {lang: catalog[key] for lang, catalog in catalogs.items() if key in catalog}
        strings[plist_key] = {"extractionState": "manual",
                              "localizations": {lang: unit(text) for lang, text in texts.items()}}
    return {"sourceLanguage": SOURCE_LANGUAGE, "strings": strings, "version": "1.0"}


def xcconfig(catalogs: dict[str, dict]) -> str:
    lines = [f"// {HEADER}", "// English Info.plist texts; InfoPlist.xcstrings translates them.", ""]
    for plist_key, key in INFO_PLIST.items():
        text = catalogs[SOURCE_LANGUAGE][key]
        if "//" in text or "$(" in text or "\n" in text:   # a comment, a variable or a line break in an xcconfig
            raise SystemExit(f"{key}: text cannot be written to an xcconfig: {text!r}")
        lines.append(f"INFOPLIST_KEY_{plist_key} = {text}")
    return "\n".join(lines) + "\n"


def swift_catalog(catalogs: dict[str, dict]) -> str:
    english = catalogs[SOURCE_LANGUAGE]
    keys = sorted(k for k in english if k.startswith(PREFIXES))
    lines = [f"// {HEADER}", "", "public enum MessageCatalog {",
             "    /// Parameters of each key with arguments, in the order of the positional specifiers.",
             "    public static let arguments: [String: [MessageArgument]] = ["]
    for key in keys:
        args = arguments(english[key])
        if args:
            items = ", ".join(f"MessageArgument({json.dumps(name)}, {json.dumps(spec) if spec else 'nil'})"
                              for name, spec in args)
            lines.append(f"        {json.dumps(key)}: [{items}],")
    lines += ["    ]", "", f"    /// Keys whose \"{PLURAL_COUNT}\" argument selects a plural form.",
              "    public static let pluralKeys: Set<String> = ["]
    lines += [f"        {json.dumps(k)}," for k in keys if isinstance(english[k], dict)]
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def dump(document: dict) -> str:
    # Xcode's own formatting, so opening the catalog in Xcode does not rewrite it.
    return json.dumps(document, ensure_ascii=False, indent=2, separators=(",", " : "), sort_keys=True) + "\n"


def outputs() -> dict[Path, str]:
    catalogs = load_catalogs()
    return {RESOURCES / "Localizable.xcstrings": dump(localizable(catalogs)),
            RESOURCES / "InfoPlist.xcstrings": dump(info_plist(catalogs)),
            XCCONFIG: xcconfig(catalogs),
            SWIFT_CATALOG: swift_catalog(catalogs)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="only report whether the files are up to date")
    args = parser.parse_args(argv)
    stale = []
    for path, content in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if args.check and stale:
        print("out of date (run python scripts/locales_to_xcstrings.py): " + ", ".join(stale), file=sys.stderr)
        return 1
    for name in ([] if args.check else stale):
        print(f"wrote {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
